balena-io/balena-base-ui

Dockerfile, README.md
Change-type: minor
Signed-off-by: Pagan Gazzard <page@resin.io>
=> Update to resin-base v4.3.0

Dockerfile
=> Update nginx to 1.14.2

Dockerfile
=> Update yarn to 1.13.0-1

.resinci.yml, README.md, circle.yml
=> Rename to balena

.github/CODEOWNERS
Connects-to: #28
Signed-off-by: Heds Simons <heds@balena.io>
=> codeowners: Add frontend team as codeowners

Dockerfile
=> Update open-balena-base to v7.0.2

.gitignore, .versionbot/CHANGELOG.yml, package-lock.json, repo.yml
=> Add changelog.yml and repo.yml for nested changelogs

Dockerfile
Update open-balena-base from 7.2.0 to 7.2.1
=> Update open-balena-base to '7.2.1'

circle.yml
=> Faster CI builds

Dockerfile
=> Update to nginx 1.18

Dockerfile
=> Remove Yarn

Dockerfile
Update open-balena-base from 11.2.0 to 11.3.0
See: https://docs.google.com/spreadsheets/d/1nyvLWrFnZQCelKhdyR9XlFIQnRtXdVXKvmb7qoAjrww/edit#gid=0
=> Update open-balena-base to 11.3.0

Dockerfile
Update open-balena-base from 11.3.10 to 11.3.11
=> Update open-balena-base to 11.3.11

Dockerfile
Update open-balena-base from 11.3.11 to 11.3.12
=> Update open-balena-base to 11.3.12

Dockerfile
Update open-balena-base from 12.0.0 to 12.0.1
=> Update open-balena-base to 12.0.1

Dockerfile
=> Remove all possible default nginx configs

Dockerfile
> (WIP) testing on ab77/balena-on-balena branch
Update open-balena-base from 12.0.3 to 12.1.3
Change-type: minor
=> Update open-balena-base to 12.1.3

repo.yml
=> Fix url for repo.yml

.github/workflows/flowzone.yml
Signed-off-by: Kyle Harding <kyle@balena.io>
=> flowzone: Inherit secrets from Org

.github/workflows/flowzone.yml, Dockerfile
Update open-balena-base from 14.7.2 to 15.0.0
Change-type: major
=> Update open-balena-base to 15.x and nginx to 1.24

repo.yml
=> Update repo.yml for nested changelogs
